server:
  port: 8080

spring:
  profiles.active: development

---
#export $(cat .env | xargs)
spring:
  profiles: development
  application:
    name: userservice
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driverClassName: com.mysql.jdbc.Driver
    test-on-borrow: true
    test-while-idle: true
    validation-query: select 1;
    maxActive: 5
    maxIdle: 5
    minIdle: 2
    initialSize: 0
    maxWait: 30000
    testOnReturn: false
    testWhileIdle: false
    timeBetweenEvictionRunsMillis: 5000
    minEvictableIdleTimeMillis: 60000
    removeAbandoned: false
    removeAbandonedTimeout: 60
    logAbandoned: false
  jpa:
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        ddl-auto: update
  mvc:
    throw-exception-if-no-handler-found: true
springdoc:
  api-docs:
    path: /api-docs
        
security:
  basic:
    enable: false
  ignored: /**
logging:
  file: userservice
  path: var/log  
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    org.springframework.web: ERROR
    com.projects.covid19.user: ERROR
    org.hibernate: ERROR
  